.\" (C) 2004 Ian Gulliver
.TH fdnsiplist 1 2004-02-12
.SH NAME
fdnsiplist \- resolve a hostname to a list of IPv4 addresses
.SH SYNOPSIS
.BI "fdnsiplist " <hostname>
.SH DESCRIPTION
fdnsiplist will attempt to look up a list of IPv4 addresses for
.IR hostname .
If any are found, they are printed to standard output seperated by newlines and the program exits
with return code 0.  If not, nothing is printed and the program exits
with return code 1.
.SH AUTHOR
Ian Gulliver <ian@penguinhosting.net>
.SH SEE ALSO
.BR libfiredns (3)
