.\" (C) 2004 Ian Gulliver
.TH fdnsmx 1 2004-02-12
.SH NAME
fdnsmx \- resolve an MX record of a hostname
.SH SYNOPSIS
.BI "fdnsmx " <hostname>
.SH DESCRIPTION
fdnsmx will attempt to look up a single MX record for
.IR hostname .
If one is found, it is printed to standard output and the program exits
with return code 0.  If not, nothing is printed and the program exits
with return code 1.
.SH AUTHOR
Ian Gulliver <ian@penguinhosting.net>
.SH SEE ALSO
.BR libfiredns (3)
