.\" (C) 2004 Ian Gulliver
.TH fdnsname 1 2004-02-13
.SH NAME
fdnsname \- resolve an IPv4 or IPv6 address to a hostname
.SH SYNOPSIS
.BI "fdnsname " "<IP address>"
.SH DESCRIPTION
fdnsname will attempt to look up a single hostname for
.IR "IP address" 
(which is an IPv4 address in dotted-quad format or an IPv6 address in
colon-seperated format).  If one is found, it is printed to standard output and the program exits
with return code 0.  If not, nothing is printed and the program exits
with return code 1.
.SH AUTHOR
Ian Gulliver <ian@penguinhosting.net>
.SH SEE ALSO
.BR libfiredns (3)
