.\" (C) 2002 Ian Gulliver
.TH firedns_resolveip6 3 2002-03-31
.SH NAME
firedns_resolveip6 \- Resolve a hostname to an IPv6 address
.SH SYNOPSIS
.B #include <firedns.h>
.br
.B -lfiredns
.LP
.BI "struct in6_addr *firedns_resolveip6(const char * const " "name" ")"
.br
.BI "struct in6_addr *firedns_resolveip6_r(const char * const " "name" ")"
.SH DESCRIPTION
firedns_resolveip6() attempts to resolve the hostname
.I name
to an IPv6 address.
.SH RETURN VALUE
Returns a pointer to an internal static
.I struct in6_addr
that contains the IP address of
.I name
in binary format, or
.I NULL
on error.
.SH AUTHOR
Ian Gulliver <ian@penguinhosting.net>
.SH SEE ALSO
.BR libfiredns (3)
