.\" (C) 2002 Ian Gulliver
.TH firedns_resolvemx 3 2002-03-31
.SH NAME
firedns_resolvemx \- Resolve an MX record of a hostname
.SH SYNOPSIS
.B #include <firedns.h>
.br
.B -lfiredns
.LP
.BI "char *firedns_resolvemx(const char * const " "name" ")"
.br
.BI "char *firedns_resolvemx_r(const char * const " "name" ")"
.SH DESCRIPTION
firedns_resolvemx() attempts to resolve an MX record
for the hostname
.IR name .
.SH RETURN VALUE
Returns a pointer to an internal static
.I char *
that contains a MX record of
.IR name ,
or
.I NULL
on error.
.SH AUTHOR
Ian Gulliver <ian@penguinhosting.net>
.SH SEE ALSO
.BR libfiredns (3)
